# Generated by Django 5.0.1 on 2024-01-17 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.TextField(max_length=100)),
                ('preco_produto', models.FloatField()),
                ('categoria_produto', models.TextField(max_length=100)),
                ('em_estoque', models.BooleanField(default=False)),
                ('data_in', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
